# docker-compose.yml
version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: investment_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

volumes:
  postgres_data: